### PR TITLE
Edits to the discussion section

### PR DESCRIPTION
**Pull request by jeizenga**
I made a few moderately substantial changes to content here. First, I cut the material on alt contigs. For one, it more or less parroted some material in the introduction. I also felt like it wasn't an emphasis of the actual experiments we did--I don't think any of them were comparing to alt contig based methods.

I also cut some content about variant interpretation and consistent representation of variation. Mostly, I just felt like that material was underdeveloped. Some of the points were hard for me to understand. If we decide to go back on this decision, I do think the points would need to be fleshed out to be interpretable by a general audience.

I have some concerns about section talking about using haplotypes. It doesn't have a lot of detail about how haplotypes would be used for mapping or for variant calling. Without that, it more or less amounts to "if mapping were better variant calling would be better". That feels kinda weak to me. I think this section is another one that should either be shored up or cut.

I also have a comment in the text recommending that we cut some points about BayesTyper, but y'all can read it there.

### CODE REVIEW

**Comment by eldariont** [comment]
Thanks for all these good suggestions which improve the section a lot in my opinion.

Regarding alt contig-based methods I believe that SMRT-SV2 is one of these methods so it might make sense to make the difference to variant graphs clear (https://github.com/EichlerLab/smrtsv2/blob/master/GENOTYPE.md).

**Comment by glennhickey** [comment]
Agreed on most counts.  I just committed a few further cuts and changes in response. 

We do compare vs the alt-contigs approach with smrt-sv2, but never really pursued it too far past the accuracy.  There were a few mapping experiments (which didn't pan out) and size comparison experiments (which didn't happen) that would have given us more meat for discussion.  As it is, there's not much.

**Comment by jmonlong** [comment]
Thanks for the changes, it looks much much better. 

About the haplotype/mapper tease part, do you think we can find a way to say that it's definitely going to get better with vg getting better (not like many methods that dies right after publication)? Even if it's not backed with details on how, saying that one asset of this approach is that it belongs to this larger dynamic project.

**Comment by glennhickey** [comment]
I popped in a general sentence about vg growing and getting better.

**Pull request merged**
