### PR TITLE
Edits and comments for results section

### PR DESCRIPTION
**Pull request by jonassibbesen**
Here are my edits and comments for the results section. The structure and flow is much better now compared to the first time I read the manuscript. 

I noticed that both "call set" and "callset" is used in the manuscript (not only results section). I have not changed it since I did not know which spelling you prefer (I think both are correct). I have used callset in my edits.

### CODE REVIEW

**Comment by eldariont** [comment]
Excellent comments! You pointed me to a mistake I've made when switching from gold standard-based  to sample graph-based evaluation. I think I should filter out all non-SV calls from the callsets before constructing the sample graphs in order to really compare SV genotyping performance and not general genotyping performance. I will fix this and clarify the manuscript accordingly.

**Comment by eldariont** [comment]
I thought that it's maybe better to put my changes on the yeast part into a separate PR. Therefore, I removed Jonas' two comments for now and will address them there.
There is one remaining comment on Panel 1. Once this is addressed, we can probably merge this PR?!

**Comment by glennhickey** [comment]
Yeah, we want to push to get this posted to bioarxiv today, so let's merge
what we can now. . no problem to pull out remaining comments into separate
pr's or issues.

**Comment by jmonlong** [comment]
I agree. 

Fig1b should be fixed but the comment reappeared. I'll double-check and merge.

**Pull request merged**
