### PR TITLE
Edit introduction

### PR DESCRIPTION
**Pull request by jeizenga**
I did a little rearranging here too. Some of the transitions didn't really flow in a logical way to me. I also broke up or reorganized a number of paragraphs. My general feeling was that they were a bit long and meandering. It feels much more punchy to me now.

### CODE REVIEW

**Comment by jmonlong** [comment]
Thanks, it does fell more punchy. Shorter sentences!

I'm not sure about moving the part about the traditional methods back to after introducing genome graphs. It creates a back and forth between linear/graph approaches: 

1. SV and challenges with mapping to linear genome
1. Genome graphs.
1. Traditional methods based on mapping to linear genome.
1. We used genome graphs to...

I thought it made more sense to talk about the linear reference approach first, both the challenges and existing methods, and then introduce genome graphs to finish with the outline that says " we used genome graphs ...".

1. SV and challenges with mapping to linear genome
1. Traditional methods based on mapping to linear genome.
1. Genome graphs.
1. We used genome graphs to...

What do others think?

**Comment by jeizenga** [comment]
I see what you're saying. To be honest, I don't super love the way the section around the SV typing methods turned out either. I was more motivated by the flow of the paragraphs earlier in the introduction, which I do feel is a bit smoother now. What if we moved the traditional methods paragraph into the new paragraph break I made? Then it would be:

1. Despite their importance, SVs remain much more poorly studied...
2. Traditional SV genotypers...
3. Representing structural variation poses an additional challenge...
4. The catalog of known SVs in human is quickly expanding...

**Comment by jeizenga** [comment]
The traditional methods paragraph might also benefit from a topic sentence that explicitly ties the methods to the challenges we discuss in the previous paragraph. Something along the lines of "Traditional SV genotypers start from reads that were mapped to a reference genome. They then use mapping artifacts that are indicative of the challenges of mapping to SVs as evidence to detect the SVs".

**Comment by glennhickey** [comment]
@jmonlong I just took a stab at addressing your concern while keeping most of @jeizenga's other edits.

**Comment by jmonlong** [comment]
Looks good, thanks. 

I just changed one present tense to past in the outline. We mix up both present and past but this one felt wrong. I left present tense for when we say "vg is something" and past when we say we did something.

**Pull request merged**
